config/routes.rb
Rails.application.routes.draw do
	resources :customers
	resources :catalogs
	resources :orders
	resources :payments
	resources :shipments
	root 'customers#home'
end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
	validates :name, presence: true
	validates :price, presence: true
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  def index
    if Figaro.env.execute_raw_querry == "true"
      Rails.logger.info("Executing native querry")
      @catalogs = Catalog.find_by_sql('select * from catalogs')
      @catalogs = Catalog.all.paginate(page: params[:page], per_page: 5)
    else
      Rails.logger.info("Executing ruby statments")
      @catalogs = Catalog.paginate(page: params[:page], per_page: 5)
    end
  end

  def new
    @catalog = Catalog.new
  end

  def show
    if Figaro.env.execute_raw_querry == "true"
      Rails.logger.info("Executing native querry")
      @catalog =  Catalog.find_by_sql("select * from catalogs where id = #{ params[:id] }").first
    else
      Rails.logger.info("Executing ruby statments")     
      @catalog = Catalog.find(params[:id])
    end
  end

  def create
   @catalog = Catalog.new(catalog_params)

         # TODO This is not returning sql result
      if Figaro.env.execute_raw_querry == "true"
      Rails.logger.info("Executing native querry")
      @catalog = ActiveRecord::Base.connection.execute("insert into catalogs(name, price) values('#{@catalog.name}','#{@catalog.price}')")
      redirect_to :action => 'index'
     else
      Rails.logger.info("Executing ruby statments")
      if @catalog.save
        redirect_to :action => 'index'
      else

        flash[:success] = "unable to save"
        render :action => 'new'
      end
    end
  end

  def edit
    if Figaro.env.execute_raw_querry == "true"
      Rails.logger.info("Executing native querry")
      @catalog =  Catalog.find_by_sql("select * from catalogs where id = #{ params[:id] }").first
    else
      Rails.logger.info("Executing ruby statments")     
      @catalog = Catalog.find(params[:id])
    end
  end

  def update
    @catalog  = Catalog.new(catalog_params)
     # TODO This is not returning sql result
          if Figaro.env.execute_raw_querry == "true"
              Rails.logger.info("Executing native querry")
              @catalog = ActiveRecord::Base.connection.execute("update catalogs set name = '#{@catalog.name}', price = '#{@catalog.price}' where id = #{ params[:id]}")
              redirect_to :action => 'show'
          else
           Rails.logger.info("Executing ruby statments")     
            if @catalog.update_attributes(catalog_params)
              redirect_to :action => 'show' , :id => @catalog
              flash[:success] = " Updated "
            else
              render :action => 'edit'
             end
          end
  end

  def destroy
    if Figaro.env.execute_raw_querry == "true"
      Rails.logger.info("Executing native querry")
      @catalog =  ActiveRecord::Base.connection.execute("delete from catalogs where id = #{ params[:id] }")
      flash[:success] = "Item deleted successfully"
      redirect_to :action => 'index'
    else
      Rails.logger.info("Executing ruby statments")
      Catalog.find(params[:id]).destroy
      flash[:success] = "Item deleted"
      redirect_to :action => 'index'
    end
  end


  def catalog_params
    params.require(:catalog).permit(:name, :price)
  end

end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/views/catalogs/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="well"><center><h2 >Add Food Item</h2></center></div>
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@catalog) do |f| %>
    
    <div class="form-group">
      <%= f.label :item_name  %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

   <div class="form-group">
      <%= f.label :price  %>
      <%= f.number_field :price, class: 'form-control' %>
    </div>

      <div class="form-group">
      <%= f.submit "save changes", class: "btn btn-primary", :onclick =>"alert('Item Updated..!')" %>
    </div>

    <% end %>
  </div>
</div>
</div>
</div>

app/views/catalogs/index.html.erb
<body>
	<div class="page-content">
	<div class="header"><h2 style="font-family: Georgia">MENU</h2></div>
	<div class="container">
		<div class="table-responsive">     
	  	 <table class="table table-hover">
	    	<thead>
	      		<tr>
	      			<th>ID</th>
		        	<th>Name</th>
		        	<th>Price</th> 
	      		</tr>
	    	</thead>
	   		<% @catalogs.each do |c| %>
		    <tbody>
		    	<tr>
		    		<td><%= c.id %></td>
		    		<td><%= link_to c.name.capitalize, {:action =>'show' ,:id => c.id} %></td>
			    	<td>Rs.<%= c.price %>/-</td>
			    </tr> 
			 </tbody>
		    <% end %>
		 </table>
		</div>
		</div>
		<div class="container">
		<%= link_to '<button type="button" class="btn btn-primary">Add Items</button>'.html_safe, new_catalog_path %>
	</br>
	 <%= will_paginate @catalogs %>
	</div>
</div>
</div>
</body>

app/views/catalogs/new.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="well"><center><h2>Add Food Item</h2></center></div>
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@catalog) do |f| %>
    
    <div class="form-group">
      <%= f.label :item_name  %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

   <div class="form-group">
      <%= f.label :price  %>
      <%= f.number_field :price, class: 'form-control' %>
    </div>

      <div class="form-group">
      <%= f.submit "Add item", class: "btn btn-primary" %>
    </div>

    <% end %>
  </div>
</div>
</div>
</div>

app/views/catalogs/show.html.erb
<div class="container">
<div class="jumbotron">
<h3><%= @catalog.name.capitalize %></h3>
<p><div class="well">
	<strong>Price : Rs.  </strong> <%= @catalog.price %>/-</br>
</div>
</p>
</div>
<%= link_to '<button type="button" class="btn btn-primary">Update</button>'.html_safe, edit_catalog_path %>
<%= link_to '<button type="button" class="btn btn-danger" >Delete</button>'.html_safe, catalog_path , method: :delete , :onclick => "alert('Item successfully deleted..!')" %>
</div>