config/routes.rb
Rails.application.routes.draw do
	resources :customers
	resources :catalogs
	resources :orders
	resources :payments
	resources :shipments
	root 'customers#home'
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :orders
	validates :name, presence: true
	validates :email, presence: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		if Figaro.env.execute_raw_querry == "true"
			Rails.logger.info("Executing native querry")
			@customers = Customer.find_by_sql('select * from customers')
			@customers = Customer.all.paginate(page: params[:page], per_page: 5)
		else
			Rails.logger.info("Executing ruby statments")
			@customers = Customer.all.paginate(page: params[:page], per_page: 5)
		end
	end

	def show
		if Figaro.env.execute_raw_querry == "true"
			Rails.logger.info("Executing native querry")
			@customer =  Customer.find_by_sql("select * from customers where id = #{ params[:id] }").first
		else
			Rails.logger.info("Executing ruby statments")			
			@customer = Customer.find(params[:id])
		end
		render :not_found if @customer.nil?
	end

	def new
		@customer = Customer.new
	end

	def create
		@customer = Customer.new(customer_params)

         # TODO This is not returning sql result
         if Figaro.env.execute_raw_querry == "true"
			Rails.logger.info("Executing native querry")
		 	@customer = ActiveRecord::Base.connection.execute("insert into customers(name, address, email, phone_no) values('#{@customer.name}', '#{@customer.address}', '#{@customer. email}', '#{@customer.phone_no}')")
		 	redirect_to :action => 'index'
		 else
		 	Rails.logger.info("Executing ruby statments")
			if @customer.save
				redirect_to :action => 'index'
			else

				flash[:success] = "unable to save"
				render :action => 'new'
			end
		end
	end

	def customer_params
		params.require(:customer).permit(:name, :email, :address, :phone_no)
	end

	def edit
		if Figaro.env.execute_raw_querry == "true"
			Rails.logger.info("Executing native querry")
			@customer =  Customer.find_by_sql("select * from customers where id = #{ params[:id] }").first
		else
			Rails.logger.info("Executing ruby statments")			
			@customer = Customer.find(params[:id])
		end
	end

	def update
		# @existing_customer  = Customer.find(params[:id])
		@customer = Customer.new(customer_params)

		 # TODO This is not returning sql result
         if Figaro.env.execute_raw_querry == "true"
			Rails.logger.info("Executing native querry")
		 	@customer = ActiveRecord::Base.connection.execute("update customers set name = '#{@customer.name}', address = '#{@customer.address}', email = '#{@customer.email}', phone_no = '#{@customer.phone_no}' where id = #{ params[:id]}")
		 	redirect_to :action => 'show'
		else
			Rails.logger.info("Executing ruby statments")		 	
			if @customer.update_attributes(customer_params)
				redirect_to :action => 'show' , :id => @customer
				flash[:success] = " Updated "
		    else
			    render :action => 'edit'
			end
		end
	end

	def destroy
		if Figaro.env.execute_raw_querry == "true"
			Rails.logger.info("Executing native querry")
			@customer =  ActiveRecord::Base.connection.execute("delete from customers where id = #{ params[:id] }")
			flash[:success] = "Customer deleted successfully"
			redirect_to :action => 'index'
		else
			Rails.logger.info("Executing ruby statments")
			Customer.find(params[:id]).destroy
			flash[:success] = "Customer deleted"
			redirect_to :action => 'index'
		end
	end

	def home
	end

end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customers/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="well"><center><h2>Customer Details</h2></center></div>
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@customer) do |f| %>
    
    <div class="form-group">
      <%= f.label :name  %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

      <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

      <div class="form-group">
      <%= f.label :phone_no %>
      <%= f.text_field :phone_no, class: 'form-control' %>
    </div>

      <div class="form-group">
      <%= f.submit "save changes", class: "btn btn-primary" %>
    </div>

    <% end %>
  </div>
</div>
</div>
</div>

app/views/customers/home.html.erb
<body class="home-page">
	<div class="opacity-for-background">
	<div class="centered">
		<h1 > Welcome To Foodie </h1>
	</div>
	<div class="centered1">
		<h3> Eat healthy, Live healthy..!</h3> 
	</div>
</div>
</body>

app/views/customers/index.html.erb
<div class="page_content">
	<div class="header"><h2 style="font-family: Georgia">LIST&nbsp; OF&nbsp; CUSTOMERS</h2></div>
	<div class="container">
		<div class="table-responsive">     
	  	 <table class="table table-hover">
	    	<thead>
	      		<tr>
	      			<th>ID</th>
		        	<th>Name</th>
		        </tr>
	    	</thead>
	   		<% @customers.each do |c| %>
		    <tbody>
		    	<tr>
		    		<td><%= c.id %></td>
		    		<td><%= link_to c.name.capitalize, {:action =>'show' ,:id => c.id} %></td>
			    </tr> 
			 </tbody>
		    <% end %>
		 </table>
		</div>
	</div>
	<div class="container">
		<%= link_to '<button type="button" class="btn btn-primary">Add</button>'.html_safe, new_customer_path %>
	</br>
	<%= will_paginate %> 
	</div>
</div>
</div>

app/views/customers/new.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="well"><center><h2>Customer Details</h2></center></div>
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@customer) do |f| %>
    
    <div class="form-group">
      <%= f.label :name  %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

      <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

      <div class="form-group">
      <%= f.label :phone_no %>
      <%= f.text_field :phone_no, class: 'form-control' %>
    </div>

      <div class="form-group">
      <%= f.submit "submit", class: "btn btn-primary" %>
    </div>

    <% end %>
  </div>
</div>
</div>
</div>

app/views/customers/show.html.erb
<div class="container">
<div class="jumbotron">
<h1><%= @customer.name.capitalize %></h1>
<p><div class="well">
	<strong>Email: </strong> <%= @customer.email %><br/>
	<strong>Address: </strong> <%= @customer.address.capitalize %><br/>
	<strong>Phone_no: </strong> <%= @customer.phone_no %><br/>
</div>
</p>
</div>
<%= link_to '<button type="button" class="btn btn-primary">Update</button>'.html_safe, edit_customer_path %>
<%= link_to '<button type="button" class="btn btn-danger">Delete</button>'.html_safe, customer_path, method: :delete %>
</div>