config/routes.rb
Rails.application.routes.draw do
	resources :customers
	resources :catalogs
	resources :orders
	resources :payments
	resources :shipments
	root 'customers#home'
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer
	has_one :payment
	has_one :shipment
	has_many :order_details

	
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
		@order = Order.new
	end


	def index
		if Figaro.env.execute_raw_querry == "true"
	      Rails.logger.info("Executing native querry")
	      @orders = Order.find_by_sql('select * from orders')
	      @orders = Order.all.paginate(page: params[:page], per_page: 5)
	    else
	      Rails.logger.info("Executing ruby statments")
	      @orders = Order.all.paginate(page: params[:page], per_page: 5)
   		end
	end

	def show
		if Figaro.env.execute_raw_querry == "true"
	      Rails.logger.info("Executing native querry")
	      @order =  Order.find_by_sql("select * from orders where id = #{ params[:id] }").first
	    else
	      Rails.logger.info("Executing ruby statments")     
	      @order = Order.find(params[:id])
	    end
	end

	def create
		@order = Order.new(order_params)
		Rails.logger.info("customer id= #{@order.customer_id}")
		Rails.logger.info("payment type= #{params[:payment_type]}")
		Rails.logger.info("staff name= #{params[:staff_name]}")
		Rails.logger.info("phone number= #{params[:phone_no]}")
		Rails.logger.info("catalog_id= #{params[:catalog_id]}")
		Rails.logger.info("quantity= #{params[:quantity]}")

	         # TODO This is not returning sql result
		    Rails.logger.info("Executing native querry")
		    #@order = ActiveRecord::Base.connection.execute("insert into orders(customer_id) values('#{@order.customer_id})'")
		    #redirect_to :action => 'index'
		    @order.save
		    payment = Payment.new
		    payment.payment_type = params[:payment_type]
		    payment.status = "Pending"
		    payment.order = @order
		    payment = payment.create(skip_execute_raw_query: true)

		    shipment = Shipment.new
		    shipment.staff_name = params[:staff_name]
		    shipment.phone_no = params[:phone_no]
		    shipment.status = "Created"
		    shipment.order = @order
		    shipment = shipment.create(skip_execute_raw_query: true)

		    # @order.payment_id = payment.id
		    # @order.shipment_id = shipment.id
		    #@order.save

		    order_detail = OrderDetail.new(@order.id,params[:catalog_id_1], params[:quantity_1])
		    order_detail.create


		    order_detail = OrderDetail.new(@order.id,params[:catalog_id_2], params[:quantity_2])
		    order_detail.create

		 	@order = ActiveRecord::Base.connection.execute("update orders inner join(select order_id, sum(quantity*price) total_price from order_details inner join catalogs on order_details.catalog_id=catalogs.id group by order_id) d on orders.id = d.order_id set orders.total_cost = d.total_price; ")



		    redirect_to :action => 'index'

	end

	def update
		@order = Order.new(order_params)

		 # TODO This is not returning sql result
         if Figaro.env.execute_raw_querry == "true"
			Rails.logger.info("Executing native querry")
		 	redirect_to :action => 'show'
		else
			Rails.logger.info("Executing ruby statments")		 	
			if @customer.update_attributes(customer_params)
				redirect_to :action => 'show' , :id => @customer
				flash[:success] = " Updated "
		    else
			    render :action => 'edit'
			end
		end
	end


	def destroy
		if Figaro.env.execute_raw_querry == "true"
			Rails.logger.info("Executing native querry")
			@order =  ActiveRecord::Base.connection.execute("delete from orders where id = #{ params[:id] }")
			flash[:success] = "Order deleted successfully"
			redirect_to :action => 'index'
		else
			Rails.logger.info("Executing ruby statments")
			Order.find(params[:id]).destroy
			flash[:success] = "Order deleted"
			redirect_to :action => 'index'
		end
	end

	def order_params
		params.require(:order).permit(:customer_id)
	end
	
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="page_content">
	<div class="header"><h2 style="font-family: Georgia">ORDERS</h2></div>
	<div class="container">
		<div class="table-responsive">     
	  	 <table class="table table-hover">
	    	<thead>
	      		<tr>
	      			<th>ID</th>
					<th>Customer Name</th>
			        <th>Total Amount</th>
			        <th>Payment Status</th>
			        <th>Shipment Status</th>
		        </tr>
	    	</thead>
	   		<% @orders.each do |o| %>
		    <tbody>
		    	<tr>
		    		<td><%= o.id %></td>
		    		<td><%= link_to o.customer.name.capitalize, {:action =>'show' ,:id => o.id} %></td>
		    		<td>Rs <%= o.total_cost %>.00 /-</td>
		    		<td><%= o.payment.status %></td>
			    	<td><%= o.shipment.status %></td>
			    </tr> 
			 </tbody>
		    <% end %>
		 </table>
		</div>
	</div>
	<div class="container">
		<%= link_to '<button type="button" class="btn btn-primary">New Order</button>'.html_safe, new_order_path %>
	</br>
	<%= will_paginate %> 
	</div>
</div>
</div>

app/views/orders/new.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="well"><center><h2>Order Now</h2></center></div>
    <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= form_for(@order) do |f| %>

    <div class="form-row">
      <div class="col-md-6">
      <%= f.label :"Customer ID" %>
      <%= f.text_field :customer_id, class: 'form-control' %>
    </div>
    <div class="col-md-6">
      <%= f.label :"Payment_type" %>
      <%= select_tag "payment_type" , options_for_select(['cash','paytm']), class: 'form-control' %>
    </div>
  </div>

    <div class="form-row">
    <div class="col-md-6">  
      <%= f.label :"Staff Name" %>
      <input type="text" name="staff_name" class="form-control">
     <%# <%= text_field :staff_name, class: 'form-control' %>
    </div>
    <div class="col-md-6">
      <%= f.label :"Phone Number" %>
      <input type="text" name="phone_no" class="form-control">
     <%# <%= text_field :phone_no, class: 'form-control' %>
    </div>
  </div>

    <div class="form-row">
      <div class="col-md-6">
      <%= f.label :"First Item ID" %>
      <input type="text" name="catalog_id_1" class="form-control">
    </div>
    <div class="col-md-6">
      <%= f.label :"Quantity" %>
      <input type="number" name="quantity_1" class="form-control">
    </div>
  </div>
 
    <div class="form-row">
      <div class="col-md-6">
      <%= f.label :"Second Item ID " %>
      <input type="text" name="catalog_id_2" class="form-control">
    </div>
    <div class="col-md-6">
      <%= f.label :"Quantity" %>
      <input type="number" name="quantity_2" class="form-control">
    </div>
  </div>

    <div class="form-row">
      <div class="col-md-3">
      <%= f.submit "order now", class: "btn btn-primary"  %>
    </div>

    <% end %>
  </div>
</div>
</div>
</div>

app/views/orders/show.html.erb
<div class="container">
<div class="jumbotron">
<p><div class="well">
<h1><center>Order Details</center></h1>
</div>
	<strong>Order ID: </strong> <%= @order.id %><br/>
	<strong>Customer Name:</strong><%= @order.customer.name.capitalize %></br>
	<strong>Item 1: </strong> <%= @order.order_details.first.catalog.name.capitalize %>
	<strong style="margin-left: 40px">Quantity: </strong> <%= @order.order_details.first.quantity %><br/>
	<strong>Item 2: </strong> <%= @order.order_details.last.catalog.name.capitalize %>
	<strong style="margin-left: 40px">Quantity: </strong> <%= @order.order_details.last.quantity %><br/>
	<h2> Payment Details</h2>
	<strong>Total cost: </strong>Rs <%= @order.total_cost %>.00 /-<br/>
	<strong>Payment Type: </strong> <%= @order.payment.payment_type %><br/>
	<strong>Payment Status: </strong> <%= @order.payment.status.capitalize %><br/>
	<h2> Shipment Details</h2>
	<strong>Delivery Person Name: </strong> <%= @order.shipment.staff_name.capitalize %><br/>
	<strong>Phone No. : </strong> <%= @order.shipment.phone_no %><br/>
	<strong>Shipment Status: </strong> <%= @order.shipment.status.capitalize %><br/>
</p>
</div>
<div class="b1">
<%= link_to '<button type="button" class="btn btn-danger">Delete</button>'.html_safe, order_path, method: :delete %>
</div>
</div>