config/routes.rb
Rails.application.routes.draw do
	resources :customers
	resources :catalogs
	resources :orders
	resources :payments
	resources :shipments
	root 'customers#home'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <nav>
      <ul class="nav navbar-nav navbar-left">
         <li style="font-size: 20px" class="<%= 'active' if current_page?('/') %>"><%= link_to "FOODIE", "/" %></li>
        <li class="<%= 'active' if current_page?(catalogs_path) %>"><%= link_to "Menu", catalogs_path %></li>
         <li class="<%= 'active' if current_page?(customers_path) %>"><%= link_to "Customers", customers_path %></li>
        <li class="<%= 'active' if current_page?(orders_path) %>"><%= link_to "Orders", orders_path %></li>
         <li class="<%= 'active' if current_page?(payments_path) %>"><%= link_to "Payments", payments_path %></li>
         <li class="<%= 'active' if current_page?(shipments_path) %>"><%= link_to "Shipments", shipments_path %></li>
      </ul>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodOrderingSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  		<%= render 'layouts/header' %>
	  <%= yield %>
  </body>
</html>